name: Build Resume

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX Document
        uses: dante-ev/latex-action@latest
        with:
          root_file: Resume_AdrianLeung.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Upload Updated Resume
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST -H "X-Api-Key: $API_KEY" -F "resume=@Resume_AdrianLeung.pdf" https://api.adrianleung.dev/resume

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: Resume_AdrianLeung.pdf
